### PR TITLE
fix: add `/usr/local/lib64` to LD search path

### LINKED ISSUE #1886: Add standard build directories to LD_LIBRARY_PATH for manylinux_2_28?
I'm looking to transition from manylinux2014 to manylinux_2_28 in [this project PR](https://github.com/shapely/shapely/pull/2363), however I noticed that LD_LIBRARY_PATH is different, such that auditwheel cannot find libraries installed to `/usr/local`.

I.e. compare LD_LIBRARY_PATH between these two images:

    $ docker run -it --rm quay.io/pypa/manylinux2014_x86_64:2025.08.02-1 printenv | grep LD_
    LD_LIBRARY_PATH=/opt/rh/devtoolset-10/root/usr/lib64:/opt/rh/devtoolset-10/root/usr/lib:/opt/rh/devtoolset-10/root/usr/lib64/dyninst:/opt/rh/devtoolset-10/root/usr/lib/dyninst:/usr/local/lib64

    $ docker run -it --rm quay.io/pypa/manylinux_2_28_x86_64:2025.12.07-1 printenv | grep LD_
    LD_LIBRARY_PATH=/opt/rh/gcc-toolset-14/root/usr/lib64:/opt/rh/gcc-toolset-14/root/usr/lib:/opt/rh/gcc-toolset-14/root/usr/lib64/dyninst:/opt/rh/gcc-toolset-14/root/usr/lib/dyninst

The later is missing `/usr/local/lib64`. Is this intentional? Or is it a recurrence of an old issue #26?

### PR DESCRIPTION
**Pull request by mwtoews**
This (untested) fix adds `/usr/local/lib64` to `manylinux` images (except i686, which doesn't have this dir).

Fixes #1886

### CODE REVIEW

File: docker/build_scripts/install-runtime-packages.sh [hunk 1]
```diff
@@ -163,6 +163,9 @@ if [ "${BASE_POLICY}" == "manylinux" ]; then
 	# as LD_LIBRARY_PATH does not seem enough.
 	# c.f. https://github.com/pypa/manylinux/issues/1022
```
Comment (mayeut) [inline docker/build_scripts/install-runtime-packages.sh]:
```suggestion
	# c.f. https://github.com/pypa/manylinux/issues/1022
	# we also want to keep those standard build directories searched by ld
	# c.f. https://github.com/pypa/manylinux/issues/1886
```
